### PR TITLE
add data and modify some config

### PR DESCRIPTION
**Pull request by dawkinsmw**

### CODE REVIEW

**Comment by dawkinsmw** [comment]
Hey @mmcky,  I believe this branch now has everything that is needed for a successful jb_build.

**Comment by dawkinsmw** [comment]
In term's of troubleshooting, is the best place to look the: 
🔍 Inspect the deploy log: https://app.netlify.com/sites/keen-wozniak-c08666/deploys/62258250492aa0000859b694

**Comment by mmcky** [comment]
@dawkinsmw you won't get preview builds until #3 is merged for the workflow support

**Comment by mmcky** [comment]
So if you're happy with this we can merge this PR and then update #3 with the latest master

**Pull request merged**
