### PR TITLE
MAINT: Upgrade Julia and Python

### PR DESCRIPTION
**Pull request by mmcky**
This PR

- upgrades to `julia=1.9`
- upgrades to `python=3.11`
- uses latest anaconda

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac this is now building but failing due to `quantecon` package not being in the install path. (I used a generic anaconda environment in this update). 

The companion package doesn't need `quantecon` to run so it also is not a dependency.

Would you like me to add the `quantecon` package to the source files (similar to lectures) or add it as a dependency in the companion package https://github.com/QuantEcon/quantecon-book-networks/tree/main?

**Comment by jstac** [comment]
Thanks @mmcky .  If you could add it as a dependency in the library that would be great.

**Comment by mmcky** [comment]
@jstac would you like me to update `quantecon-book-network` to `1.0` as this book is about to be published right?

**Comment by jstac** [comment]
Yes please @mmcky .

If the Julia kernel is specified perhaps we should bump it to 1.9.

**Comment by mmcky** [comment]
> If the Julia kernel is specified perhaps we should bump it to 1.9.

This PR updates the julia version to `1.9` 👍

**Comment by jstac** [comment]
Thanks @mmcky , please proceed when ready.

**Comment by mmcky** [comment]
- [x] release `quantecon-book-networks==1.0` to PyPI

**Comment by mmcky** [comment]
There are some execution issues in

`ch_fpms`

Screenshot 2023-11-20 at 2 37 12 pm

- [ ] update code as removed in `v3.0` of networkx https://networkx.org/documentation/stable/release/release_3.0.html

`ch_opt`

There is a module dependency not met. 

@jstac would you like all dependencies for the book to be requested by `quantecon-book-networks` companion package?

```python
ModuleNotFoundError: No module named 'ot'
```

- [ ] fix issue

**Comment by mmcky** [comment]
@jstac fixes have been made. 

There was some minor book side code changes -- if you need to propagate to book?

See #57

**Pull request merged**
