### PR TITLE
Fixed a few typos in notebooks

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by jstac** [comment]
Great job @shlff , many thanks.

Just one change please: headings should never end in full stops.  For example,

```
### This is a heading.
```

should be 

```
### This is a heading
```

Would you mind to remove the ones you added and any more that you see?

**Comment by pitmonticone** [comment]
Sure, no problem.

**Review by pitmonticone — COMMENTED** [review]
Removed "." in H3 lines

**Review by pitmonticone — COMMENTED** [review]
Fix typos in text and LaTeX.

**Comment by jstac** [comment]
Very nice work @pitmonticone , much appreciated!

**Comment by pitmonticone** [comment]
Thank you all for creating this great resource!

**Comment by jstac** [comment]
Thanks a pleasure @pitmonticone .  I hope you find it useful. I'm just editing a new version of the PDF and I'll thank you in the acknowledgements.  I'll republish the website later today.

We're now looking for a publisher so that we can have a formal hardcopy, but we will keep a free PDF available.

**Comment by pitmonticone** [comment]
Oh, so kind of you. Thank you very much!

**Pull request merged**
