### PR TITLE
Update codebooks

### PR DESCRIPTION
**Pull request by HengchengZhang**
Hi @jstac, this PR fixes the inconsistency between codebook and pdf version of the book.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @HengchengZhang !

I see some errors in the build.  See, e.g., https://6464713ee573496d09b60e21--keen-wozniak-c08666.netlify.app/ch_intro.html

**Comment by jstac** [comment]
The last figure on https://6464713ee573496d09b60e21--keen-wozniak-c08666.netlify.app/ch_production.html is still using Canada...

**Comment by HengchengZhang** [comment]
Thanks @jstac for pointing these out.

All the figures should still be old ones (and they should be the same as the ones on the book)because the updates in `quantecon-book-networks` package hasn't been deployed.

But I'm looking through every error to see if there are anything that is not related to the package.

**Comment by HengchengZhang** [comment]
Hi @jstac, all the changes have been applied and is ready to merge.

**Comment by jstac** [comment]
Thanks @HengchengZhang .

I'm not seeing all the figures -- e.g., https://6476f84f7b16d776e614667f--keen-wozniak-c08666.netlify.app/ch_intro.html

**Comment by HengchengZhang** [comment]
> https://6476f84f7b16d776e614667f--keen-wozniak-c08666.netlify.app/ch_intro.html

Hi @jstac, this is still because the package `quantecon_book_networks`(`qbn`) hasn't been updated yet.

I'm sorry I forget to tell you and here's what we need to do now:

1. merge [this](https://github.com/QuantEcon/quantecon-book-networks/pull/7) PR.
2. publish this release on PyPI (which can only be done by @mmcky).
3. then the changes will be applied in the codebooks.

Shu helped me finish local testing of `v0.5` which is what I showed you yesterday.

If you also want to do a local testing there are instructions in [here](https://github.com/QuantEcon/book-networks/pull/52/commits/17f0b00df3a7fff9b8f8c9792bb29c2dfd399da7#diff-7ac8e8241e127d0878da7edce85eb752de6fe8dc9f05b7886e93f112d0a1d6ed) with the testing environment [here](https://github.com/QuantEcon/book-networks/pull/52/commits/6066d27a6c0b0229e0a1b6aa15d09117dea3e050#diff-0154ce303f6e30b3853632bed8f56c5277b487bebae26416bebf90ff250c37a8).

(I deleted them before making this PR.)

**Comment by mmcky** [comment]
> Shu helped me finish local testing of v0.5 which is what I showed you yesterday.

Thanks @shlff and @HengchengZhang 

Thanks for doing the local testing before we release the package to PyPI. I will merge this now and setup a release.

**Pull request merged**
