### PR TITLE
Add Chinese Translation of Text

### PR DESCRIPTION
**Pull request by mmcky**
This PR migrates the work @natashawatkins did in #45

### CODE REVIEW

**Comment by mmcky** [comment]
@shlff would you mind checking the `Chinese` on the front page? 

Screenshot 2023-02-24 at 12 04 17 pm

**Comment by shlff** [comment]
> @shlff would you mind checking the `Chinese` on the front page?
> 
> Screenshot 2023-02-24 at 12 04 17 pm

Thanks @mmcky . The text is in simplified Chinese and equivalent to that you can click here to download the pdf version of the textbook.

**Comment by mmcky** [comment]
thanks @shlff

**Comment by mmcky** [comment]
thanks @natashawatkins for this update to the companion site.

**Pull request merged**
