### PR TITLE
MAINT: Update to use matplotlib config from package

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates the code_book to use

```
quantecon_book_networks.config("matplotlib")
```

https://github.com/QuantEcon/quantecon-book-networks/pull/1

@shlff would you mind updating this PR with the changes once the above is merged and released on PyPI

### CODE REVIEW

**Comment by mmcky** [comment]
`v0.4` is now available on PyPI. 

https://pypi.org/project/quantecon_book_networks/

**Comment by mmcky** [comment]
@jstac given the new `matplotlib` configuration requires latex do you want to:

1. build the `pdf` on `github actions` when the site is built
2. manually update the `pdf`

**Comment by mmcky** [comment]
@shlff I updated `ch_opt` as an example for you. 

https://6279e6f6628a22319b5f49f2--keen-wozniak-c08666.netlify.app/ch_opt.html

Is this the intended behaviour?

**Comment by shlff** [comment]
> https://6279e6f6628a22319b5f49f2--keen-wozniak-c08666.netlify.app/ch_opt.html

Thanks @mmcky . Sorry for my late reply. This is exactly what we want.

**Comment by mmcky** [comment]
@shlff would you mind updating the other pages?

**Comment by mmcky** [comment]
Merging this in. @jstac if you'd like the PDF to be `auto` built via Github Actions - let me know. Otherwise I'll assume you'll update via push to `pdf`.

**Comment by shlff** [comment]
> @shlff would you mind updating the other pages?

Sure @mmcky .

**Pull request merged**
