### PR TITLE
ENH: Update Front Page

### PR DESCRIPTION
**Pull request by mmcky**
This is currently a trial space to see how we could use `sphinx-design` or if we should use custom `html` which can be embedded in `intro.md` directly using a raw directive. 

@jstac something like this might be nice

https://www.istockphoto.com/vector/abstract-network-background-gm865632716-143650653

- [x] update `julia==1.7` for the latest `julia` release
- [x] mockup of front page using `sphinx-design`
- [x] link the PDF card to `arXiv`

### CODE REVIEW

**Comment by jstac** [comment]
Thanks Matt.  I like the image.

**Comment by mmcky** [comment]
@jstac it's rough but a reasonable starting point. What do you think?

Screen Shot 2022-03-21 at 3 34 27 pm

**Comment by mmcky** [comment]
@jstac here is the updated screenshot
Screen Shot 2022-03-21 at 3 34 27 pm

- [ ] check why `Julia` is failing
- [ ] update PDF with link to `arXiv`

**Comment by mmcky** [comment]
@jstac ok I think this is good to go for now.

**Comment by mmcky** [comment]
@jstac I have now updated this to point to the `arXiv` hosted PDF

**Comment by mmcky** [comment]
@jstac I will merge this so it's available on `gh-pages` and we can iterate on any modifications.

**Pull request merged**
