### PR TITLE
Add chinese version of textbook

### PR DESCRIPTION
**Pull request by natashawatkins**
- Added Chinese version of Networks textbook
- Updated links to be more HTML5-like

### CODE REVIEW

**Comment by natashawatkins** [comment]
@mmcky is my downloads link correct? I used the same structure as for the original textbook.

**Comment by mmcky** [comment]
@natashawatkins this won't actually build a preview as it is coming from a `fork`. If you use local branches then a preview will generate for you.

There is one issue you will need to update the GitHub action workflows in `.github/workflows` to copy the `Chinese` pdf across. 

https://github.com/QuantEcon/book-networks/blob/bfddf9cad91a45e74cc159a923137061329f14ba/.github/workflows/publish.yml#L107

and 

https://github.com/QuantEcon/book-networks/blob/bfddf9cad91a45e74cc159a923137061329f14ba/.github/workflows/ci.yml#L97

**Comment by mmcky** [comment]
@natashawatkins forgot to say you have collaborator status to this repo now.

**Comment by mmcky** [comment]
replace by #46

**Pull request closed without merging**
