### PR TITLE
Review

### PR DESCRIPTION
**Pull request by dawkinsmw**

### CODE REVIEW

**Comment by dawkinsmw** [comment]
@mmcky I think that we are getting pretty close with this one. 
How do I publish to the github pages main site (it doesn't seem to do it after merging a PR to main).

**Comment by dawkinsmw** [comment]
@mmcky for the plotly plot, I gave up and used the svg renderer which worked on my local (but no interactivity).
But I think it is causing issues for the github actions build.
Any thoughts?

**Comment by dawkinsmw** [comment]
@jstac 
I think this PR has everything except still missing code for Figure 6.3:
image

**Comment by mmcky** [comment]
thanks @dawkinsmw -- I have some ideas re: `plotly` so I will take a look on Monday and try get that supported.

**Comment by jstac** [comment]
Hi @dawkinsmw , that figure is made with tikz.  You can find the source here: https://github.com/jstac/networks_text/blob/main/tikz/infsup.tex

Feel free to omit it.  It's tangential to the main text.

**Comment by mmcky** [comment]
> @mmcky for the plotly plot, I gave up and used the svg renderer which worked on my local (but no interactivity).
> But I think it is causing issues for the github actions build.
> Any thoughts?

`SVG` is a good short term solution. Can you open an issue to document `plotly` issue (i.e. which pages are impacted) and I will talk with Aakash to see where we are up to with `plotly` in quantecon-book-theme.

**Comment by mmcky** [comment]
@dawkinsmw did you want to add anything to this branch before its merged?

**Pull request merged**
