### PR TITLE
Add julia to github workflow

### PR DESCRIPTION
**Pull request by dawkinsmw**

### CODE REVIEW

**Comment by dawkinsmw** [comment]
@mmcky I don't know how to write project and manifest .toml files. 
Given the list of packages is short, I thought hardcoding them in the workflow could be a workaround.
Let me know if this isn't appropriate.

**Comment by mmcky** [comment]
yeah me either :-) -- I would just install (in similar fashion to `IJulia`) using `Pkg.add`

**Comment by dawkinsmw** [comment]
Awesome, I think that is what I did

**Comment by mmcky** [comment]
Looks Great - thanks @dawkinsmw

**Comment by mmcky** [comment]
@dawkinsmw it will also need to be added to the `publish.yml` workflow

**Pull request merged**
