### PR TITLE
GA: Enable Publish Workflows to build for gh-pages

### PR DESCRIPTION
**Pull request by mmcky**

### CODE REVIEW

**Comment by mmcky** [comment]
@dawkinsmw this PR is setting up both a `ci.yml` workflow for generating previews of the site, and `publish.yml` workflow for publishing to `gh-pages` branch which can host the website via GitHub Pages. I have defined the software environment in `environment.yml`. 

I am currently getting some missing file errors for:

- [ ] `data/csv_files/use_15_2019.csv`
- [ ] `../figures_source/commercial-aircraft-sitcr2-7924-yr2019/sitcr2-7924-aircraft-network-2019.gexf`

**Comment by mmcky** [comment]
@dawkinsmw there are a few execution errors that will need to be fixed. 

**ch_intro**

```
ModuleNotFoundError: No module named 'initialize'
```

**ch_opt**

```
ModuleNotFoundError: No module named 'ot'
```

**pkg_funcs```

```
NameError: name 'cm' is not defined
```

**Comment by dawkinsmw** [comment]
@mmcky ch_intro and pkg_funcs should be patched in main now.

**Comment by dawkinsmw** [comment]
@mmcky looks like there is still a problem with ch_into.

How did you find the above errors? Were you able to access the log files such as: /home/runner/work/book-networks/book-networks/_build/html/reports/ch_intro.log?

Once I can see the logs, is the workflow to patch the issue in main and then merge main into this branch?

**Comment by mmcky** [comment]
hey @dawkinsmw it can be easier to setup a local version of the `environment.yml` and run it locally. 

I think the only two final `warnings` are:

```
/Users/mmcky/work/quantecon/book-networks/code_book/intro.md:7: WARNING: 'myst' reference target not found: 
/Users/mmcky/work/quantecon/book-networks/code_book/intro.md:13: WARNING: 'myst' reference target not found:
```

just some links to fix. 

Then we should be warning free :-)

**Comment by dawkinsmw** [comment]
Hey @mmcky I cleared out the landing page should resolve the errors. 
Have you had a chance to look at sphynx design for the front page?

**Comment by mmcky** [comment]
@dawkinsmw no I haven't had time to try out `sphinx-design`. Feel free to put a suggestion together if you have time. Otherwise I will look into it over the weekend.

**Pull request merged**
